### ISSUE TITLE
No open source license

### ISSUE THREAD

**Issue by dbalatero** [usrbinnc/netcat-cpi-kernel-module#5]
Good point from twitter: https://twitter.com/chris_bloke/status/458764337083985921

@blucia0a

We should add a license. I usually use MIT, but not sure what the best license is for kernel modules come to think of it.

GPL? BSD? Apache?

**Comment by bkuhn** [comment]
Actually, the license of an Linux module is GPL, since it's based on Linux.  I believe they should explicitly state this, however, to make it clear.  Also, [see issue 8 as well](https://github.com/usrbinnc/netcat-cpi-kernel-module/issues/8) which relates to this issue.

This issue is resolved by putting a copy of the GPL at the top-level, and ideally adding a note to each source file that indicates it's licensed under GPL.

**Comment by winny-** [comment]
> This issue is resolved by putting a copy of the GPL at the top-level, and ideally adding a note to each source file that indicates it's licensed under GPL.

:+1:

This kernel module is amazing!

**Comment by dbalatero** [comment]
I'll jump over to #8

**Comment by blucia0a** [comment]
Closing this because the discussion took place in issue #8
